version : 2
models:
    - name: raw_customer
    - name: raw_order
sources:
    - name: jaffle_shop
      database: RAW
      schema: jaffle_shop
      tables:
        - name: customers
        - name: orders